### ISSUE TITLE
Print a useful error message when plugin does not publish to central

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/plugin-gradle#10]
**Description:**
When there is a SNAPSHOT version or a timestamped version, then the implementation just returns without any acknowledgement to the user. Sometimes, this will be problematic when there are release failures. Better to add a useful print statement or a warning here.

https://github.com/ballerina-platform/plugin-gradle/blob/537440ff5ea167b96f7089737e9d9fa26af79b63/src/main/groovy/io/ballerina/plugin/BallerinaPlugin.groovy#L240

**Comment by ThisaruGuruge** [comment]
Ideally, this should throw an exception, and mark the build as a failure.
