### ISSUE TITLE
Gradle task to return an intermediate pack

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/plugin-gradle#21]
**Description:**
Some people may need to test some use cases with an actual Ballerina distribution during the development cycle. Currently, to get that pack we have to build Ballerina distribution with new changes. Therefore, it is better to introduce a new task to return a new pack with the module itself is being packed.

For example, let say someone it building I/O and this new task should return a distribution with I/O itself.

**References**
- https://github.com/ballerina-platform/module-ballerina-grpc/blob/a84ecbb220e4adce3c036f053ce6ddb28ad10c60/grpc-compiler-plugin-tests/build.gradle#L91
- https://github.com/ballerina-platform/ballerina-distribution/blob/33a68ddec534fef0ed3b5d145201656c6c77d328/ballerina/build.gradle#L157

**Comment by niveathika** [comment]
This was addressed in https://github.com/ballerina-platform/plugin-gradle/pull/55
