### ISSUE TITLE
Unable to pass different module name

### ISSUE THREAD

**Issue by LakshanKarunathilake** [ballerina-platform/plugin-gradle#72]
**Description:**
I initially mentioned the project name as `observe-ballerian` and it successfully built the project and generated the artifact. But due to another subproject name change I had to update the project name to `observe-internal-ballerina`. When I try to build with  this project name plugin did not create the buildArtifact in the bala_unzipped folder.

**Steps to reproduce:**
The configurations I provided was
```
ballerina {
    packageOrganization = ballerinai
    module = observe
    langVersion = ballerinaLangVersion
    customTomlVersion = "0.0.0"
}
```

**Affected Versions:**
plugin version 0.14.2

**OS, DB, other environment details and versions:**
Ubuntu

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/33195

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
This behaviour is expected. As the ballerina project needs to be named as `packageName`-ballerina
